### ISSUE TITLE
balancing incorrect

### ISSUE THREAD

**Issue by robaho** [AppliedGo/balancedtree#2]
The balancing code is incorrect, and leads to unbalanced trees. Give the following balanced tree, with the non-zero  balance factor shown in parens
```
          3(1)
    1                 5(1)
0     2           4       6(1)
                                  7
```
Then add node 8. Which causes a the balance factor at 6 to become 2, which rebalances, and 3 becomes 2 which rebalances with a rotateLeft, giving the following tree
```
                 5
       3                 7
    1     4          6       8
0      2
``` 
This is a balanced tree, except the structure has the balance factor of nodes 5 and 3 at 0, when they should both be -1. The problem is that the rotateLeft() (and rotateRight()) sets the bf to 0 of both nodes. This is not correct, and as more nodes are added the tree becomes increasingly out of balance (you can write a test cases that adds 150k nodes in order, which should have a tree height of 18, and the height is actually 15000+

By in order, I mean string order, so mykey1, mykey2... mykey10, mykey11 - so not strictly in increasing order.

**Comment by robaho** [comment]
Btw, I've seen other AVL implementations that store the BF rather than the height in the node. The new BF after rotation can still be calculated directly in O(1) but none of the implementations described the algorithm in detail, so I changed my version to store the height in each node, and calculate the bf dynamically - easier to understand for me.

**Comment by robaho** [comment]
Btw, after the rotation these nodes can only have a bf of 0, 1 or -1 so you just need the formula... still, I gave it a shot but it wasn’t obvious to me

**Comment by christophberger** [comment]
Hi Robert, thanks for raising that issue. I am currently writing tests in preparation of the fix. I am indeed thinking of switching to storing the height in the nodes rather than the balance factor. You are right, this seems easier to follow. 
And yes, for any node in a balanced tree, the BF is either 0, 1, or -1. Not only the root node must meet the balance criteria but every node of the tree.

**Comment by robaho** [comment]
@christophberger  you might want to look at my tree.go in [keydb](https://github.com/robaho/keydb). It is essentially your code modified to store the height instead.

I'm glad you were able to reproduce - I couldn't get a handle on the poor performance and just never thought to look at the tree implementation.

**Comment by christophberger** [comment]
😱Whoa, now I feel guilty of almost having sabotaged a promising project by spreading subtle bugs! Sorry to have wasted your time. This will teach me omitting test files for "obviously clear" code :-)

**Comment by christophberger** [comment]
After three years of being blocked by full-time work and other tasks, I finally got the time to fix the balancing issue. Also changed from recording the balance to recording the height, as per https://github.com/AppliedGo/balancedtree/issues/2#issuecomment-443016497.
